name: Build and push docker image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: login to dockerhub
        uses: echo "${{secrets.DOCKER_PASSWORD}}" || docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: build docker image
        uses: docker build -t ${{secrets.DOCKER_USERNAME}}/myapp:latest .
      - name: push docker image
        uses: docker push ${{secrets.DOCKER_USERNAME}}/myapp:latest
